spring:
  application:
    name: resilience4j_protect_api

  threads:
    virtual:
      enabled: true

  boot:
    admin:
      client:
        url: http://localhost:8888

resilience4j.ratelimiter:
  instances:
    apiRestController:
      limitForPeriod: 10        # Maximum 10 requests
      limitRefreshPeriod: 60s  # Time window is 60 seconds
      timeoutDuration: 0       # If limit exceeded, fail immediately (timeout)
      registerHealthIndicator: true
      eventConsumerBufferSize: 100

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always